Feature/fix lane select
sbgisen/autoware_ai_planning pull request #20
Opened 2023-03-30 10:32 UTC by nyxrobotics

## Summary

- fix #12
- fix #16

## Detail
もう少し綺麗に書く方法あれば提案いただけると幸いです

## Impact

## Test

  

## Attention

2023-03-31 00:27 UTC, Tacha-S requested changes

2023-03-31 00:27 UTC, Tacha-S commented on lane_planner/nodes/lane_select/lane_select_core.cpp
> -  sub1_ = nh_.subscribe("traffic_waypoints_array", 1, &LaneSelectNode::callbackFromLaneArray, this);
remapで十分だと思います。

2023-03-31 00:27 UTC, Tacha-S commented on lane_planner/nodes/lane_select/lane_select_core.cpp
> +        std::get<0>(tuple_vec_.at(i)).waypoints.at(j).pose = msg->lanes.at(i).waypoints.at(j).pose;
`std::get<0>(tuple_vec_.at(i)) = msg->lanes.at(i)` ではだめなんですか？

2023-03-31 00:27 UTC, Tacha-S commented on lane_planner/nodes/lane_select/lane_select_core.cpp
> +    uint32_t lanes_size = std::min(tuple_vec_.size(), msg->lanes.size());
あまり用途的にレーンのサイズが変わったりはしないと思いますが、
落ちないようにということを考えると、
`current_lane_idx_ >= lanes_size`もしくは`current_lane_idx_ >= msg->lanes.size()`の条件を満たすときは上の分岐に入っていないとまずいと思います。

2023-04-03 06:50 UTC, nyxrobotics commented on lane_planner/nodes/lane_select/lane_select_core.cpp
> -  sub1_ = nh_.subscribe("traffic_waypoints_array", 1, &LaneSelectNode::callbackFromLaneArray, this);
下記でlaunchファイルでremapするように変更し、ここでのソースコードの変更は戻しました
https://github.com/sbgisen/outdoor_navigation_tools/pull/36

2023-04-03 06:50 UTC, nyxrobotics commented on lane_planner/nodes/lane_select/lane_select_core.cpp
> +        std::get<0>(tuple_vec_.at(i)).waypoints.at(j).pose = msg->lanes.at(i).waypoints.at(j).pose;
変更しました。

2023-04-03 06:52 UTC, nyxrobotics commented on lane_planner/nodes/lane_select/lane_select_core.cpp
> +    uint32_t lanes_size = std::min(tuple_vec_.size(), msg->lanes.size());
316c314f5b40442545f3a5e92944a147fcdb7db4 にて例外処理を追加しました。

2023-04-05 01:28 UTC, Tacha-S approved these changes

2023-04-05 01:29 UTC, merged