Feature/aster angle limit
sbgisen/autoware_ai_planning pull request #28
Opened 2023-04-13 14:00 UTC by nyxrobotics

## Summary
asterで異常な経路が出るのを防ぐための例外処理を追加し、パラメータで有効・無効を切替可能にしました。
詳細はissueを参照してください

- fix #24

2023-04-14 07:11 UTC, Tacha-S requested changes

2023-04-14 07:11 UTC, Tacha-S commented on astar_search/src/astar_search.cpp
> +      double next_theta = current_an->theta + state.rotation;
ここの変更必要なくなっていると思うので戻してください。
modifyThetaの範囲もお願いします。

2023-04-14 07:11 UTC, Tacha-S commented on astar_search/src/astar_search.cpp
> +          (enable_path_length_limit_ && move_distance > path_length_limit_))
距離の方のパラメータは`time_limit`のパラメータの調整では不十分ですか？

2023-04-14 07:48 UTC, nyxrobotics commented on astar_search/src/astar_search.cpp
> +      double next_theta = current_an->theta + state.rotation;
この２点は回避経路算出時のデバッグ情報で角度の情報current_an->thetaを表示するために残したい変更なのですが別PRにしたほうが良いでしょうか

2023-04-14 07:56 UTC, nyxrobotics commented on astar_search/src/astar_search.cpp
> +          (enable_path_length_limit_ && move_distance > path_length_limit_))
`search_time`はばらつきが大きいことと、Gazeboと実機でおそらく結果が変わるので難しいように思います。

2023-04-14 08:05 UTC, Tacha-S commented on astar_search/src/astar_search.cpp
> +      double next_theta = current_an->theta + state.rotation;
debug時に確認したいだけであればlocalでの変更にとどめておいても良くないですか？

2023-04-14 08:13 UTC, Tacha-S commented on astar_search/src/astar_search.cpp
> +          (enable_path_length_limit_ && move_distance > path_length_limit_))
調整の難易度が高いのはたしかにそうだと思います。
ですが、このパラメータを増やすことがどれだけ有効なのかがあまりわかっていません。
`path_length_limit_` が必要なケースなにかあげられますか？

2023-04-14 09:09 UTC, nyxrobotics commented on astar_search/src/astar_search.cpp
> +          (enable_path_length_limit_ && move_distance > path_length_limit_))
issueで挙げている例はすべて`path_angle_limit`のみの場合と、`path_length_limit`のみの場合どちらでも除去可能です。角度or距離のどちらで絞るべきかは状況によるような気がしていて、今はセットで一個の機能だと思っています。元のwaypointの形状やコストマップの広さによっても変わると予想されます。

2023-04-14 09:15 UTC, nyxrobotics commented on astar_search/src/astar_search.cpp
> +      double next_theta = current_an->theta + state.rotation;
確かにcurrent_an->thetaのデバッグ情報は見たところでパラメータ調整に関連しないので削除しようと思います。
`modifyTheta`についてですが、`move_angle`で角度の偏差の絶対値を加算する際に-pi〜piへ正規化するのに流用していたのですが別関数追加するほうが見やすいでしょうか

2023-04-14 09:28 UTC, Tacha-S commented on astar_search/src/astar_search.cpp
> +      double next_theta = current_an->theta + state.rotation;
> modifyThetaについてですが、move_angleで角度の偏差の絶対値を加算する際に-pi〜piへ正規化するのに流用していた

これはどこで行っていますか？

2023-04-14 09:44 UTC, nyxrobotics commented on astar_search/src/astar_search.cpp
> +      double next_theta = current_an->theta + state.rotation;
失礼しました、`state.rotation`は最初から-pi〜piだったのでmodifyThetaかけてませんでした。戻して何も問題ないので戻します。

2023-04-14 09:47 UTC, Tacha-S commented on astar_search/src/astar_search.cpp
> +          (enable_path_length_limit_ && move_distance > path_length_limit_))
距離で絞らなければならない状況がやはりわからないです。
角度のみで十分なのに、より柔軟性に欠ける変更をセットと称して追加しようとしていませんか？

> 元のwaypointの形状やコストマップの広さによっても変わると予想されます。

これもそのとおりで、どうにかできれば嬉しいです。
例えば`move_angle/move_distance`でいい感じにしきい値取れたりはしないですか？

2023-04-14 10:38 UTC, nyxrobotics commented on astar_search/src/astar_search.cpp
> +          (enable_path_length_limit_ && move_distance > path_length_limit_))
`path_length_limit`と`path_angle_limit`でどちらが優位性があるかはなんとも言えないと思います。

#24 の例は割合的に見ると距離のほうが差が大きく、この場合`path_length_limit`で制限する方法が容易と判断できます。これは旋回半径が大きいのに対しコストマップが小さめなので、迂回経路が出た際の距離の変化が大きいことが原因と予想しています。一方で旋回半径が小さいロボットの場合は迂回経路で`path_length_limit`が変化しにくく、`path_angle_limit`で制限するほうが容易な状態が発生すると予想できます。

2023-04-17 00:34 UTC, Tacha-S commented on astar_search/src/astar_search.cpp
> +          (enable_path_length_limit_ && move_distance > path_length_limit_))
> https://github.com/sbgisen/autoware_ai_planning/issues/24#issuecomment-1506855408は割合的に見ると距離のほうが差が大きく、この場合path_length_limitで制限する方法が容易

絶対的な差は距離ですが、相対的には距離が28.9->36.9に約1.25倍されると角度も12.3->15.1と約1.25倍で大差はないと思います。
ですが、この議論終着点なさそうなので一旦取り込みます。

2023-04-17 00:35 UTC, Tacha-S approved these changes

2023-04-17 00:35 UTC, merged