Feature/fill waypoints nearest area
sbgisen/autoware_ai_planning pull request #37
Opened 2023-07-07 08:35 UTC by Alpaca-zip

## Summary
- 以下のissueに関連して、最初のwaypointに乗るまで障害物を無視する問題を修正しました。
https://github.com/sbgisen/wheeltec_robot/issues/277

## Detail
- ロボットの現在地からvelocity_setで購読する`/safety_waypoints`の最初のウェイポイントまでの間にウェイポイントを追加する処理を追加しました。この追加により、最初のwaypointに乗るまでの間に障害物がある場合でも、減速および停止することが出来ます。
- ベースのウェイポイントの間隔がwaypoint_loader側で`resample_interval`としてパラメータが用意されているので、ここで新しく追加するウェイポイントの間隔も`fill_waypoints_interval`としてパラメータ化しました。

## Impact
- この変更により、パラメータの追加が発生するので、wheeltec_robot側にもパラメータの追加に関するPRを出します。

## Test
* [x] 竹芝オフィスの一周経路でのナビゲーションで動作確認

## Attention
@gakutasu  
私が対応した[autoware_ai_planning](https://github.com/sbgisen/autoware_ai_planning)における2023/07/03に実施した走行までの修正内容はこのPRで最後になります。

2023-07-11 00:44 UTC, Tacha-S requested changes

2023-07-11 00:44 UTC, Tacha-S commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +    new_waypoint.pose.pose.position.x =
ユーザーが`fill_waypoints_interval`を指定しているにもかかわらず、
distance/num_waypointsで丸められているのが気になります。
waypointの始点から現在地へのベクトルを`fill_waypoints_interval`ずつ伸ばしながらwaypoint置いたほうがいいと思います。

2023-07-11 00:44 UTC, Tacha-S commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +    lane_update.waypoints.push_back(w);
```suggestion
  lane_update.waypoints.resize(num_waypoints-2+lane.waypoints.size());
  lane_update.waypoints.insert(lane_update.waypoints.end(), lane.waypoints.begin(), lane.waypoints.end());
```

2023-07-11 00:44 UTC, Tacha-S commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +  for (int i = 1; i < num_waypoints - 1; i++)
1からnum_waypoints-2まで(既存のwaypointに乗る直前のintervalが長くなる)のはなぜですか？

2023-07-11 06:08 UTC, Alpaca-zip commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +  for (int i = 1; i < num_waypoints - 1; i++)
1からnum_waypoints-2でfor文を回しているのは`num_waypoints`が現在のロボットの位置と`/safety_waypoints`の最初のウェイポイントを含んでいるためです。`num_waypoints`が追加するウェイポイントの数と一致するように書き直すと以下のようになります。
```cpp
  num_waypoints = static_cast<int>(distance / distance_per_waypoint) - 1;

  for (int i = 1; i < num_waypoints + 1; i++)
  {
    double ratio = static_cast<double>(i) / (num_waypoints + 2);
    new_waypoint.pose.pose.position.x =
        pose.pose.position.x * (1 - ratio) + next_waypoint.pose.pose.position.x * ratio;
    new_waypoint.pose.pose.position.y =
        pose.pose.position.y * (1 - ratio) + next_waypoint.pose.pose.position.y * ratio;
    new_waypoint.pose.pose.position.z =
        pose.pose.position.z * (1 - ratio) + next_waypoint.pose.pose.position.z * ratio;

    lane_update.waypoints.push_back(new_waypoint);
  }
```

> ユーザーがfill_waypoints_intervalを指定しているにもかかわらず、
distance/num_waypointsで丸められているのが気になります。
waypointの始点から現在地へのベクトルをfill_waypoints_intervalずつ伸ばしながらwaypoint置いたほうがいいと思います。

こちらを反映する場合、上記の処理も変更する必要があるので一度再検討させていただきます。

2023-07-11 09:19 UTC, Alpaca-zip commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +    new_waypoint.pose.pose.position.x =
> waypointの始点から現在地へのベクトルをfill_waypoints_intervalずつ伸ばしながらwaypoint置いたほうがいいと思います。

こちらを満たすように処理を変更いたしました。

2023-07-11 10:32 UTC, Tacha-S requested changes

2023-07-11 10:32 UTC, Tacha-S commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +    lane_update.waypoints.insert(lane_update.waypoints.begin(), new_waypoint);
vectorの末尾以外へのinsertは結構重くて、できるだけ回数を少なくしたい処理の1つです。
この場合は、逆順でpush_back()していった後にstd::reverse()でvectorの順序まるごとひっくり返したほうが高速です。
https://quick-bench.com/q/qRb_ZYdi5JWk761VtWqzbePh93c

2023-07-11 11:03 UTC, Alpaca-zip commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +    lane_update.waypoints.insert(lane_update.waypoints.begin(), new_waypoint);
このようなツールがあるとは初めて知りました。勉強になります。

> vectorの末尾以外へのinsertは結構重くて、できるだけ回数を少なくしたい処理の1つです。
この場合は、逆順でpush_back()していった後にstd::reverse()でvectorの順序まるごとひっくり返したほうが高速です。

こちらの件修正いたしました。

2023-07-12 00:10 UTC, Tacha-S requested changes

2023-07-12 00:10 UTC, Tacha-S commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +    std::reverse(lane_update.waypoints.begin(), lane_update.waypoints.end());
この行while loopの外だと思います。

2023-07-12 00:39 UTC, Alpaca-zip commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +    std::reverse(lane_update.waypoints.begin(), lane_update.waypoints.end());
大変失礼いたしました。こちら修正しました。

2023-07-12 00:45 UTC, Tacha-S approved these changes, later dismissed

2023-07-12 04:35 UTC, nyxrobotics approved these changes

2023-07-12 04:44 UTC, nyxrobotics requested changes

2023-07-12 04:44 UTC, nyxrobotics commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +{
`distance_per_waypoint<=0`の時に`return 0;`してもらえるとよい気がします

2023-07-12 05:22 UTC, Alpaca-zip commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +{
こちらの件修正致しました。いかがでしょうか。

2023-07-12 05:27 UTC, Tacha-S commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +{
この機能を無効化したい場合があるのであればこれで良さそうですが、
常に有効化で問題なければコンストラクタで不正値としてエラーログとともに落としたほうがわかりやすそうです

2023-07-12 05:47 UTC, Alpaca-zip commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +{
> この機能を無効化したい場合があるのであればこれで良さそうですが、
常に有効化で問題なければコンストラクタで不正値としてエラーログとともに落としたほうがわかりやすそうです

https://github.com/sbgisen/autoware_ai_planning/blob/e89db6011ddfa0a1a55bdcafe5a13bbf609cd78f/waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp#L692
上記の後に、以下のような処理を追加するという意味でしょうか。
```cpp
if (fill_waypoints_interval <= 0)
{
  ROS_ERROR("Invalid parameter value: fill_waypoints_interval must be positive.");
  ros::shutdown();
  return 0;
}
```

2023-07-12 05:48 UTC, nyxrobotics commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +{
その点少し悩みましたが、何となく0設定時に無効にできるようにしておくのがいいと思いました。
正直こだわりはありません。

2023-07-12 05:55 UTC, Tacha-S commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +{
私もどちらでもいいのでこのままで大丈夫です。

2023-07-12 06:02 UTC, Alpaca-zip commented on waypoint_planner/src/velocity_set_lanelet2/velocity_set_lanelet2.cpp
> +{
> if (fill_waypoints_interval <= 0)
{
  ROS_ERROR("Invalid parameter value: fill_waypoints_interval must be positive.");
  ros::shutdown();
  return 0;
}

上記のような処理を足す場合には、`deceleration_search_distance`や`stop_search_distance`にも同様の処理が無いことが不自然に感じるのでこのままでも良いのではないでしょうか。

2023-07-12 06:15 UTC, nyxrobotics approved these changes

2023-07-12 06:18 UTC, Tacha-S approved these changes

2023-07-12 06:19 UTC, merged